name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-check:
    name: runner / Biome (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: action-success-test
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          workdir: ./testdata
          reporter: github-check
          level: error
          filter_mode: nofilter
          fail_on_error: true
          biome_flags: ok/
      # github-check test is judged to fail if an error occurs even if continue-on-error is set to true.
      # Therefore, the test for failure should also succeed by setting the report level to warning.
      - name: action-failure-test
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          workdir: ./testdata
          reporter: github-check
          level: warning
          filter_mode: nofilter
          fail_on_error: true
          biome_flags: error/

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / Biome (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: action-success-test
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          workdir: ./testdata
          reporter: github-pr-check
          level: error
          filter_mode: nofilter
          fail_on_error: true
          biome_flags: ok/
      # github-pr-check test is judged to fail if an error occurs even if continue-on-error is set to true.
      # Therefore, the test for failure should also succeed by setting the report level to warning.
      - name: action-failure-test
        uses: ./
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          workdir: ./testdata
          reporter: github-pr-check
          level: warning
          filter_mode: nofilter
          fail_on_error: true
          biome_flags: error/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / Biome (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: action-success-test
        name: action-success-test
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          workdir: ./testdata
          reporter: github-pr-review
          level: error
          filter_mode: nofilter
          fail_on_error: true
          biome_flags: ok/
      - id: action-failure-test
        name: action-failure-test
        uses: ./
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          workdir: ./testdata
          reporter: github-pr-review
          level: error
          filter_mode: nofilter
          fail_on_error: true
          biome_flags: error/
      - name: check-failure
        if: steps.action-failure-test.outcome == 'success'
        run: exit 1
